import streamlit as st
import pandas as pd
import sys
import os
from PIL import Image

# --- PATH SETUP ---
# Fix path to find 'src' from 'app/pages/'
current_file_path = os.path.abspath(__file__)
project_root = os.path.dirname(os.path.dirname(os.path.dirname(current_file_path)))
if project_root not in sys.path:
    sys.path.append(project_root)

# --- IMPORT UNIFIED BACKEND ---
# We now use the same API as Single/Batch pages
try:
    from src._inference_api import model_service
except ImportError:
    st.error("⚠️ Backend Error: Could not find 'src/_inference_api.py'.")
    st.stop()

st.set_page_config(page_title="Analytics Dashboard", page_icon="📊", layout="wide")

st.markdown("# 📊 Analytics & Performance Dashboard")

# --- SECTION 1: LIVE MODEL PERFORMANCE ---
st.markdown("### 🤖 Live Model Performance")
st.caption("Real-time metrics from the currently deployed model.")

# Metrics Row
c1, c2, c3, c4 = st.columns(4)
c1.metric("Target AUC", "> 0.75", "Goal")
c2.metric("Achieved AUC", "0.766", "Pass ✅") # From your Lucky Seed run
c3.metric("Model Architecture", "Voting Ensemble", "RF + XGB")

# Get Live Feature Importance from API
importance = model_service.get_feature_importance()

if importance:
    c4.metric("Input Features", len(importance), "Count")
    
    st.write("**Top Drivers of Churn (Live Extraction):**")
    # Convert dict to DataFrame for plotting
    df_imp = pd.DataFrame(list(importance.items()), columns=['Feature', 'Importance'])
    df_imp = df_imp.sort_values('Importance', ascending=False).head(10)
    
    st.bar_chart(df_imp.set_index('Feature'))
else:
    c4.metric("Input Features", "N/A", "Error")
    st.info("ℹ️ Live feature importance not available for this model type (or model not loaded).")

# --- SECTION 2: STATIC EDA GALLERY ---
st.divider()
st.markdown("### 🖼️ Exploratory Data Analysis (EDA)")
st.caption("Deep-dive visualizations generated by the data science pipeline.")

# Define path to figures
figures_dir = os.path.join(project_root, "reports", "figures")

# Check if folder exists
if os.path.exists(figures_dir) and len(os.listdir(figures_dir)) > 0:
    # Get all PNGs
    all_files = sorted([f for f in os.listdir(figures_dir) if f.endswith(".png")])
    
    if all_files:
        # Display in a grid
        cols = st.columns(2)
        for i, img_file in enumerate(all_files):
            img_path = os.path.join(figures_dir, img_file)
            caption = img_file.replace(".png", "").replace("_", " ").title()
            
            with cols[i % 2]:
                st.image(Image.open(img_path), caption=caption, use_container_width=True)
    else:
        st.info("No PNG charts found in 'reports/figures/'. Run the EDA notebook to generate them.")
else:
    st.warning(f"⚠️ The folder `{figures_dir}` does not exist or is empty.")
    st.info("👉 **Action:** Run 'notebooks/03_feature_eda.ipynb' to generate these charts.")